In [ ]:
!python -m pip install SQLAlchemy pandas

In [9]:
import sqlalchemy
import pandas as pd

conn = 'mysql://root:789124@localhost:3306/cmi'
engine = sqlalchemy.create_engine(conn)

In [18]:
hospcode = ("11053", "11008", "10670")

query = open("sql/01_select_cmi.sql", "r")
with engine.connect().execution_options(autocommit=True) as conn:
  df = pd.read_sql(sql=query.read(), con=engine, params={"hospcode": hospcode})

df

    hospcode       hospname  zone     cmi
0      10670     รพ.ขอนแก่น     7  1.9861
1      11008     รพ.ภูเวียง     7  0.5889
2      11053  รพ.กันทรวิชัย     7  0.5531
3      10670     รพ.ขอนแก่น     7  1.9928
4      11008     รพ.ภูเวียง     7  0.6032
5      11053  รพ.กันทรวิชัย     7  0.5411
6      10670     รพ.ขอนแก่น     7  2.0586
7      11008     รพ.ภูเวียง     7  0.6265
8      11053  รพ.กันทรวิชัย     7  0.5873
9      10670     รพ.ขอนแก่น     7  2.1122
10     11008     รพ.ภูเวียง     7  0.6241
11     11053  รพ.กันทรวิชัย     7  0.6334
12     10670     รพ.ขอนแก่น     7  2.0648
13     11008     รพ.ภูเวียง     7  0.6231
14     11053  รพ.กันทรวิชัย     7  0.6265

In [16]:
from datetime import datetime

now = datetime.now()
str_time = now.strftime("%Y%m%d%H%M%S")
csv_filename = f"cmi_{str_time}.csv"

df.to_csv(csv_filename, sep="|", index=False)